---

# pip Upgrade
#- name: Upgrade pip
#  pip: name=pip state=latest
#  tags: packages

- name: Add repository for Python 3.5 to the sources list
  become: true
  become_method: sudo
  become_user: root
  apt_repository: repo='ppa:fkrull/deadsnakes'
                  update_cache=yes
                  state=present

- name: Install Python 3.4 and related packages
  become: true
  become_method: sudo
  become_user: root
  apt: name={{ item }} update_cache=yes state=present
  with_items:
          - python3
          - python3-dev
          - python3-pip
          - ipython3
