---

- name: Ensure bash, OpenSSL, and libssl are the latest versions
  become: true
  become_method: sudo
  become_user: root
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
          - bash
          - openssl
          - libssl-dev
          - libssl-doc
          - tree
          - git
  tags: packages
